#[derive(Debug, Clone)]
pub struct Token {
    pub value: String,
    pub kind: TokenKind,
    pub line: u16, // needed for debugging
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum TokenKind {
    Tab,
    Comment,
    CompilerData,

    WhiteSpace,
    EndOfFile,
    NextLine,
    OpenParen,
    CloseParen,
    OpenBracket,
    CloseBracket,
    OpenCurly,
    CloseCurly,
    Comma,
    Dot,
    SemiColon,
    Colon,
    Arrow,
    Question,

    Plus,
    Minus,
    Star,
    Slash,
    Percent,

    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,

    PlusPlus,
    MinusMinus,

    Equals,
    NotEquals,
    Less,
    LessEquals,
    Greater,
    GreaterEquals,

    Not,
    And,
    Or,

    BitwiseShiftLeft,
    BitwiseShiftRight,

    Assignment,
    Reference,

    Number,
    String,
    True,
    False,

    Identifier,
    Static,
    Return,
    If,
    Else,
    While,
    For,
    Enum,
    Struct,
    Break,
    Other,
    Constant,
    Typedef,
}

impl TokenKind {
    pub fn to_str(&self) -> &str {
        match self {
            TokenKind::Tab => todo!(),
            TokenKind::Comment => todo!(),
            TokenKind::CompilerData => todo!(),
            TokenKind::WhiteSpace => todo!(),
            TokenKind::EndOfFile => todo!(),
            TokenKind::NextLine => todo!(),
            TokenKind::OpenParen => todo!(),
            TokenKind::CloseParen => todo!(),
            TokenKind::OpenBracket => todo!(),
            TokenKind::CloseBracket => todo!(),
            TokenKind::OpenCurly => todo!(),
            TokenKind::CloseCurly => todo!(),
            TokenKind::Comma => todo!(),
            TokenKind::Dot => todo!(),
            TokenKind::SemiColon => todo!(),
            TokenKind::Colon => todo!(),
            TokenKind::Arrow => todo!(),
            TokenKind::Question => todo!(),
            TokenKind::Plus => "+",
            TokenKind::Minus => "-",
            TokenKind::Star => "*",
            TokenKind::Slash => "/",
            TokenKind::Percent => "%",
            TokenKind::PlusEquals => "+=",
            TokenKind::MinusEquals => "-=",
            TokenKind::StarEquals => "*=",
            TokenKind::SlashEquals => "*=",
            TokenKind::PlusPlus => "++",
            TokenKind::MinusMinus => "--",
            TokenKind::Equals => "==",
            TokenKind::NotEquals => "!=",
            TokenKind::Less => "<",
            TokenKind::LessEquals => "<=",
            TokenKind::Greater => ">",
            TokenKind::GreaterEquals => ">=",
            TokenKind::Not => "!",
            TokenKind::And => "&&",
            TokenKind::Or => "||",
            TokenKind::BitwiseShiftLeft => "<<",
            TokenKind::BitwiseShiftRight => ">>",
            TokenKind::Assignment => "=",
            TokenKind::Reference => "&",
            TokenKind::Number => todo!(),
            TokenKind::String => todo!(),
            TokenKind::True => "true",
            TokenKind::False => "false",
            TokenKind::Identifier => todo!(),
            TokenKind::Static => todo!(),
            TokenKind::Return => todo!(),
            TokenKind::If => todo!(),
            TokenKind::Else => todo!(),
            TokenKind::While => todo!(),
            TokenKind::For => todo!(),
            TokenKind::Enum => todo!(),
            TokenKind::Struct => todo!(),
            TokenKind::Break => todo!(),
            TokenKind::Other => todo!(),
            TokenKind::Constant => todo!(),
            TokenKind::Typedef => todo!(),
        }
    }
}
